### ISSUE TITLE
Update doc with functions

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/presentation-builder#7]
https://github.com/archival-IIIF/presentation-builder/blob/master/doc/examples/collection-v3.md
https://github.com/archival-IIIF/presentation-builder/blob/master/doc/examples/image-v3.md

@kerim1: You changed resource. Now it is `id, type, value, format, language, width, height`. Before it was `id, type, format, width, height`. Was this your intention?

**Comment by kerim1** [comment]
Yes, I changed it because before we had a `Resource` and a separate `TextResource` which did not make sense because they are both resources. However, the constructor code was getting ugly with all the `undefined` properties. So I created two helper functions instead. One for "bytes" resources so to say and one for the text resources: https://github.com/archival-IIIF/presentation-builder/blob/master/src/v3/Resource.ts#L48-L55

**Comment by Sozialarchiv** [comment]
I reopened the ticket because the doc update is not yet done. I will do that.

**Comment by kerim1** [comment]
I fixed the test examples in this commit: https://github.com/archival-IIIF/presentation-builder/commit/1c58a0a2179f13a9b8d251a6cecac3c360ae19b7

**Comment by Sozialarchiv** [comment]
I am talking about the doc examples no the test examples:

https://github.com/archival-IIIF/presentation-builder/blob/master/doc/examples/collection-v3.md
https://github.com/archival-IIIF/presentation-builder/blob/master/doc/examples/image-v3.md

There are not fixed yet. I will do it.

**Comment by kerim1** [comment]
I know, but I was talking about the test examples.
